// <auto-generated />
using System;
using InternProject02.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternProject02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230216090252_ICollectionUpdate")]
    partial class ICollectionUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternProject02.Models.Announcement.AnnouncementCommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnouncementCommentBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnnouncementCommentCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnnouncementCommentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementComments");
                });

            modelBuilder.Entity("InternProject02.Models.Announcement.AnnouncementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnouncementBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnnouncementCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnnouncementCreator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnnouncementTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("InternProject02.Models.Announcement.AnnouncementCommentModel", b =>
                {
                    b.HasOne("InternProject02.Models.Announcement.AnnouncementModel", "Announcement")
                        .WithMany("Comments")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("InternProject02.Models.Announcement.AnnouncementModel", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
